kind: pipeline
type: docker
name: default

steps:
- name: testcafe
  image: testcafe/testcafe
  commands:
  - testcafe chromium *_test.js
  environment:
    ADMIN_PASSWORD:
      from_secret: admin_password
    REGULAR_PASSWORD:
      from_secret: regular_password
